### ISSUE TITLE
Don't declare queues with amq. prefix

### ISSUE THREAD

**Issue by KristjanTammekivi** [KristjanTammekivi/Haredo#91]
```
2020-05-29T07:28:21Z ERROR rabbit: ConnectionManager connection error Error: Heartbeat timeout
    at Heart.<anonymous> (/home/kristjan/projects/something/node_modules/amqplib/lib/connection.js:427:19)
    at Heart.emit (events.js:315:20)
    at Heart.EventEmitter.emit (domain.js:485:12)
    at Heart.runHeartbeat (/home/kristjan/projects/something/node_modules/amqplib/lib/heartbeat.js:88:17)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) -undefined:undefined
2020-05-29T07:28:21Z DEBUG rabbit: Consumer channel closed -undefined:undefined
2020-05-29T07:28:21Z DEBUG rabbit: ConnectionManager connection closed -undefined:undefined
2020-05-29T07:28:21Z DEBUG rabbit: ConnectionManager reopening connection -undefined:undefined
2020-05-29T07:28:21Z DEBUG rabbit: ConnectionManager connecting -undefined:undefined
2020-05-29T07:28:21Z ERROR rabbit: Consumer Failed to restart consumer OperationalError: Operation failed: QueueDeclare; 403 (ACCESS-REFUSED) with message "ACCESS_REFUSED - queue name 'amq.gen-WEXPTtK3WqDGOtjEx9tOHQ' contains reserved prefix 'amq.*'"
```

It should wipe the queue name before attempting to redeclare

**Comment by KristjanTammekivi** [comment]
Fixed with dc9a6745b324b4dba7b2e13f71dcdd9534ed6ffe
